### ISSUE TITLE
unable to build on ubuntu 16.04 

### ISSUE THREAD

**Issue by ivan2kh** [emgram769/webpipe#3]
```
[ 99%] Building C object CMakeFiles/websockets_shared.dir/lib/roles/http/server/lejp-conf.c.o
[100%] Linking C shared library lib/libwebsockets.so
[100%] Built target websockets_shared
mkdir -p objs
gcc -I/tmp/libwebsockets/build/lib/Headers -I/usr/include -Wall -O2 pipe.c -c -o objs/pipe.o
pipe.c:4:27: fatal error: libwebsockets.h: No such file or directory
compilation terminated.
Makefile:30: recipe for target 'objs/pipe.o' failed
make: *** [objs/pipe.o] Error 1
[sudo] password for ivan2kh: 
gcc  -I/usr/include -Wall -O2 pipe.c -c -o objs/pipe.o
pipe.c:4:27: fatal error: libwebsockets.h: No such file or directory
compilation terminated.
Makefile:30: recipe for target 'objs/pipe.o' failed
make: *** [objs/pipe.o] Error 1
```

**Comment by imk13** [comment]
First, you need to update build.sh
`#!/bin/bash
old_dir=$(pwd)
git clone https://github.com/warmcat/libwebsockets.git /tmp/libwebsockets
cd /tmp/libwebsockets
mkdir build
cd build
cmake ..
make
cd $old_dir
export ENV_LDFLAGS="-lssl -lcrypto -L/tmp/libwebsockets/build/lib -libwebsockets" && export STATIC_LIBWEBSOCKETS="true" && export ENV_CFLAGS="-I/tmp/libwebsockets/build/lib/Headers" && make
if [ "$1" = "--install" ]; then
  sudo make install
fi`
Then run install command
`./build.sh --install`
See if that works.

**Comment by ivan2kh** [comment]
still no success
```
gcc -I/tmp/libwebsockets/build/lib/Headers -I/usr/include -Wall -O2 objs/pipe.o -o webpipe -lssl -lcrypto -L/tmp/libwebsockets/build/lib -libwebsockets -lpthread
/usr/bin/ld: cannot find -libwebsockets
collect2: error: ld returned 1 exit status
Makefile:23: recipe for target 'webpipe' failed
make: *** [webpipe] Error 1
gcc  -I/usr/include -Wall -O2 objs/pipe.o -o webpipe  -lwebsockets -lpthread
objs/pipe.o: In function `initialize_ws_client':
pipe.c:(.text+0x515): undefined reference to `lws_client_connect'
collect2: error: ld returned 1 exit status
```

**Comment by eliafino** [comment]
not exist: /tmp/libwebsockets/build/lib/Headers
